In [7]:
import pandas as pd
import glob
import os

csv_files = glob.glob("*.csv")
print("CSV files available in Colab:")
for file_name in csv_files:
  print("-", file_name)

orders_data = pd.read_csv("Day9_Orders.csv")
customers_data = pd.read_csv("Day9_Customers.csv")
products_data = pd.read_csv("Day9_Products.csv")
print("All three datasets loaded successfully. ")

print("========== ORDERS DATASET ==========")
display(orders_data.head())
print("\nOrders shape:", orders_data.shape)
print("\nOrders columns:")
print(orders_data.columns.tolist())
print("\nOrders data types:")
print(orders_data.dtypes)

print("========== CUSTOMERS DATASET ==========")
display(customers_data.head())
print("\nCustomers shape:", customers_data.shape)
print("\nCustomers columns:")
print(customers_data.columns.tolist())
print("\nCustomers data types:")
print(customers_data.dtypes)

print("========== PRODUCTS DATASET ==========")
display(products_data.head())
print("\nProducts shape:", products_data.shape)
print("\nProducts columns:")
print(products_data.columns.tolist())
print("\nProducts data types:")
print(products_data.dtypes)

print("========== MISSING VALUES ==========")
print("Orders:")
print(orders_data.isnull().sum())
print("\nCustomers:")
print(customers_data.isnull().sum())
print("\nProducts:")
print(products_data.isnull().sum())

print("Orders columns:")
print(orders_data.columns.tolist())
print("\nCustomers columns:")
print(customers_data.columns.tolist())
print("\nProducts columns:")
print(products_data.columns.tolist())

orders_customers = pd.merge(
    orders_data,
    customers_data,
    on="Customer_ID",
    how="left"
)

print("Orders and customers merged successfully.")
display(orders_customers.head())

processed_data = pd.merge(
    orders_customers,
    products_data,
    on="Product_ID",
    how="left"
)

print("Orders, Customers, and Products merged successfully.")
display(processed_data.head())

print("========== PROCESSED DATASET ==========")
print("Shape:", processed_data.shape)
print("\nColumns:")
print(processed_data.columns.tolist())
display(processed_data.head(10))

first_half = orders_data.iloc[:len(orders_data) // 2]
second_half = orders_data.iloc[len(orders_data) // 2]
combined_orders = pd.concat(
    [first_half, second_half],
    ignore_index=True
)

print("Orders combined using concat()")
print("Original rows:", len(orders_data))
print("Combined rows:", len(combined_orders))
display(combined_orders.head())

processed_data["Order_Date"] = pd.to_datetime(
    processed_data["Order_Date"]
)
print("Oder_Date converetd to datetime.")
print(
    processed_data["Order_Date"].dtype
)

processed_data["Order_Month"] = (
    processed_data["Order_Date"].dt.month
)

display(
    processed_data[
        ["Order_Date", "Order_Month"]
    ].head()
)

processed_data["Order_Month_Name"] = (
    processed_data["Order_Date"].dt.month_name()
)
display(
    processed_data[
        ["Order_Date", "Order_Month_Name"]
    ].head()
)

processed_data["Order_Day"] = (
    processed_data["Order_Date"].dt.day
)

display(
    processed_data[
        ["Order_Date", "Order_Day"]
    ].head()
)

processed_data["Order_Day_Name"] = (
    processed_data["Order_Date"].dt.day_name()
)

display(
    processed_data[
        ["Order_Date", "Order_Day_Name"]
    ].head()
)

processed_data["Order_Year"] = (
    processed_data["Order_Date"].dt.year
)

display(
    processed_data[
        ["Order_Date", "Order_Day_Name"]
    ].head()
)

def classify_quantity(quantity):
  """Classify an order based on its quantity."""
  if quantity >= 5:
    return "Large"
  elif quantity >= 3:
    return "Medium"
  else:
    return "Small"

processed_data["Quantity_Category"] = (
    processed_data["Quantity"].apply(
        classify_quantity
    )
)

display(
    processed_data[
        ["Quantity", "Quantity_Category"]
    ].head(10)
)

processed_data["Calculated_Value"] = (
    processed_data.apply(
        lambda row: row["Quantity"] * row["Unit_Price"],
        axis=1
    )
)

display(
    processed_data[
        [
            "Quantity",
            "Unit_Price",
            "Calculated_Value"
        ]
    ].head()
)

print("========== PROCESSED DATASET MISSING VALUES ==========")
missing_values = processed_data.isnull().sum()
print(missing_values)

duplicate_count = processed_data.duplicated().sum()
print(f"Duplicate rows found: {duplicate_count}")
processed_data = processed_data.drop_duplicates()
print(
    f"Rows after removing duplicates: "
    f"{len(processed_data)}"
)

processed_data = processed_data.sort_values(
    by="Order_Date"
)

display(processed_data.head())

print("========== FINAL PROCESSED DATASET ==========")
print("Rows:", processed_data.shape[0])
print("Columns:", processed_data.shape[1])
print("\nColumn names:")
for column_name in processed_data.columns:
  print("-", column_name)

print("\nData types:")
print(processed_data.dtypes)

display(processed_data)

output_file = "processed_ecommerce_dataset.csv"
processed_data.to_csv(
    output_file,
    index=False
)

print(
    f"Processed dataset exported successfully "
    f"as {output_file}"
)

if os.path.exists(output_file):
  print("Export successful.")
  print(f"File created: {output_file}")
else:
  print("Exprot failed.")

CSV files available in Colab:
- Day9_Customers.csv
- Day9_Products.csv
- Day9_Orders.csv
All three datasets loaded successfully.
========== ORDERS DATASET ==========

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Orders shape: (120, 7)

Orders columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Orders data types:
Order_ID          object
Order_Date        object
Customer_ID       object
Product_ID        object
Quantity           int64
Payment_Method    object
Order_Status      object
dtype: object
========== CUSTOMERS DATASET ==========

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Customers shape: (30, 5)

Customers columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Customers data types:
Customer_ID        object
Customer_Name      object
City               object
Region             object
Membership_Type    object
dtype: object
========== PRODUCTS DATASET ==========

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

Products shape: (20, 5)

Products columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

Products data types:
Product_ID      object
Product_Name    object
Category        object
Unit_Price       int64
Brand           object
dtype: object
========== MISSING VALUES ==========
Orders:
Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Payment_Method    0
Order_Status      0
dtype: int64

Customers:
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
dtype: int64

Products:
Product_ID      0
Product_Name    0
Category        0
Unit_Price      0
Brand           0
dtype: int64
Orders columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']
Orders and customers merged successfully.

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

Orders, Customers, and Products merged successfully.

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

========== PROCESSED DATASET ==========
Shape: (120, 15)

Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus

Orders combined using concat()
Original rows: 120
Combined rows: 67

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,0
0,O0001,2026-02-19,C027,P019,2.0,Credit Card,Delivered,NaN
1,O0002,2026-01-25,C006,P003,2.0,Debit Card,Delivered,NaN
2,O0003,2026-02-26,C015,P004,1.0,Cash on Delivery,Delivered,NaN
3,O0004,2026-03-04,C024,P015,3.0,Net Banking,Delivered,NaN
4,O0005,2026-03-29,C025,P009,5.0,Credit Card,Delivered,NaN

Oder_Date converetd to datetime.
datetime64[ns]

  Order_Date  Order_Month
0 2026-02-19            2
1 2026-01-25            1
2 2026-02-26            2
3 2026-03-04            3
4 2026-03-29            3

  Order_Date Order_Month_Name
0 2026-02-19         February
1 2026-01-25          January
2 2026-02-26         February
3 2026-03-04            March
4 2026-03-29            March

  Order_Date  Order_Day
0 2026-02-19         19
1 2026-01-25         25
2 2026-02-26         26
3 2026-03-04          4
4 2026-03-29         29

  Order_Date Order_Day_Name
0 2026-02-19       Thursday
1 2026-01-25         Sunday
2 2026-02-26       Thursday
3 2026-03-04      Wednesday
4 2026-03-29         Sunday

  Order_Date Order_Day_Name
0 2026-02-19       Thursday
1 2026-01-25         Sunday
2 2026-02-26       Thursday
3 2026-03-04      Wednesday
4 2026-03-29         Sunday

   Quantity Quantity_Category
0         2             Small
1         2             Small
2         1             Small
3         3            Medium
4         5             Large
5         3            Medium
6         3            Medium
7         4            Medium
8         2             Small
9         2             Small

   Quantity  Unit_Price  Calculated_Value
0         2        2499              4998
1         2         899              1798
2         1        3299              3299
3         3         999              2997
4         5        3499             17495

========== PROCESSED DATASET MISSING VALUES ==========
Order_ID             0
Order_Date           0
Customer_ID          0
Product_ID           0
Quantity             0
Payment_Method       0
Order_Status         0
Customer_Name        0
City                 0
Region               0
Membership_Type      0
Product_Name         0
Category             0
Unit_Price           0
Brand                0
Order_Month          0
Order_Month_Name     0
Order_Day            0
Order_Day_Name       0
Order_Year           0
Quantity_Category    0
Calculated_Value     0
dtype: int64
Duplicate rows found: 0
Rows after removing duplicates: 120

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,...,Category,Unit_Price,Brand,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Order_Year,Quantity_Category,Calculated_Value
50,O0051,2026-01-01,C008,P017,4,Net Banking,Delivered,Sara Ahmed,Hyderabad,South,...,Sports,899,FitLife,1,January,1,Thursday,2026,Medium,3596
90,O0091,2026-01-01,C002,P011,2,Credit Card,Delivered,Zoya Khan,Delhi,North,...,Home & Kitchen,4999,CookSmart,1,January,1,Thursday,2026,Small,9998
21,O0022,2026-01-02,C023,P014,4,Net Banking,Delivered,Nikhil Sood,Chandigarh,North,...,Books,899,DataPress,1,January,2,Friday,2026,Medium,3596
105,O0106,2026-01-02,C001,P009,1,Net Banking,Delivered,Aarav Sharma,Srinagar,North,...,Home & Kitchen,3499,HomeBrew,1,January,2,Friday,2026,Small,3499
75,O0076,2026-01-03,C019,P015,1,Debit Card,Delivered,Yusuf Dar,Srinagar,North,...,Books,999,AIPress,1,January,3,Saturday,2026,Small,999

========== FINAL PROCESSED DATASET ==========
Rows: 120
Columns: 22

Column names:
- Order_ID
- Order_Date
- Customer_ID
- Product_ID
- Quantity
- Payment_Method
- Order_Status
- Customer_Name
- City
- Region
- Membership_Type
- Product_Name
- Category
- Unit_Price
- Brand
- Order_Month
- Order_Month_Name
- Order_Day
- Order_Day_Name
- Order_Year
- Quantity_Category
- Calculated_Value

Data types:
Order_ID                     object
Order_Date           datetime64[ns]
Customer_ID                  object
Product_ID                   object
Quantity                      int64
Payment_Method               object
Order_Status                 object
Customer_Name                object
City                         object
Region                       object
Membership_Type              object
Product_Name                 object
Category                     object
Unit_Price                    int64
Brand                        object
Order_Month                   int32
Order_Month_Name             object
Order_Day                     int32
Order_Day_Name               object
Order_Year                    int32
Quantity_Category            object
Calculated_Value              int64
dtype: object

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,...,Category,Unit_Price,Brand,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name,Order_Year,Quantity_Category,Calculated_Value
50,O0051,2026-01-01,C008,P017,4,Net Banking,Delivered,Sara Ahmed,Hyderabad,South,...,Sports,899,FitLife,1,January,1,Thursday,2026,Medium,3596
90,O0091,2026-01-01,C002,P011,2,Credit Card,Delivered,Zoya Khan,Delhi,North,...,Home & Kitchen,4999,CookSmart,1,January,1,Thursday,2026,Small,9998
21,O0022,2026-01-02,C023,P014,4,Net Banking,Delivered,Nikhil Sood,Chandigarh,North,...,Books,899,DataPress,1,January,2,Friday,2026,Medium,3596
105,O0106,2026-01-02,C001,P009,1,Net Banking,Delivered,Aarav Sharma,Srinagar,North,...,Home & Kitchen,3499,HomeBrew,1,January,2,Friday,2026,Small,3499
75,O0076,2026-01-03,C019,P015,1,Debit Card,Delivered,Yusuf Dar,Srinagar,North,...,Books,999,AIPress,1,January,3,Saturday,2026,Small,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,...,Electronics,1199,VoltPlus,3,March,27,Friday,2026,Medium,4796
86,O0087,2026-03-28,C006,P004,5,Cash on Delivery,Cancelled,Ishita Gupta,Bengaluru,South,...,Electronics,3299,FitTech,3,March,28,Saturday,2026,Large,16495
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,...,Home & Kitchen,3499,HomeBrew,3,March,29,Sunday,2026,Large,17495
79,O0080,2026-03-29,C026,P019,5,Debit Card,Delivered,Fatima Noor,Srinagar,North,...,Sports,2499,BatPro,3,March,29,Sunday,2026,Large,12495
36,O0037,2026-03-30,C028,P005,1,Credit Card,Delivered,Inaya Khan,Mumbai,West,...,Electronics,1199,VoltPlus,3,March,30,Monday,2026,Small,1199

Processed dataset exported successfully as processed_ecommerce_dataset.csv
Export successful.
File created: processed_ecommerce_dataset.csv